### ISSUE TITLE
An error during inference stage

### ISSUE THREAD

**Issue by egorsmkv** [sp-uhh/derevdps#1]
Hello!

I am getting an error while inference stage.

Command:

```
python enhancement.py --test_dir ../enhance-files/ --enhanced_dir ../enhanced-files-DerevDPS/ --ckpt ../derevdps-models/epoch_204.ckpt --N 50
```

The output:

```
Traceback (most recent call last):
  File "enhancement.py", line 112, in <module>
    y, A, zeta, operator, zeta_schedule = get_posterior_sampling_args(
  File "enhancement.py", line 37, in get_posterior_sampling_args
    A = kernel.forward(**kernel_kwargs)
  File "/home/yehor/ext-ml-disk/dx/derevdps/preprocessing/kernel.py", line 75, in forward
    self.sample_kernel_kwargs(**kernel_kwargs)
  File "/home/yehor/ext-ml-disk/dx/derevdps/preprocessing/kernel.py", line 81, in sample_kernel_kwargs
    self.kernel_path = join(kernel_kwargs["rir_path"], sorted(os.listdir(kernel_kwargs["rir_path"]))[kernel_kwargs["i"]])
FileNotFoundError: [Errno 2] No such file or directory: '/data/lemercier/databases/wsj0_derev_with_rir/rir/tt'
```

Is there something (RIR datatase I guess) that I need to download except the checkpoint?

**Comment by jmlemercier** [comment]
Hi @egorsmkv sorry about the delay: this is an informed dereverberation method so you do need to have access to the RIR the reverberant utterance was created with to solve the inverse problem. 
Please use the script `preprocessing/create_data.py` to reproduce the dataset which contains folders for anechoic and reverberant speech and the RIRs used to create the reverberant speech. Please then feed your corresponding test RIR folder path as argument to `self.kernel_path`

**Comment by egorsmkv** [comment]
Understood. Thank you, @jmlemercier
